# fos_rest:
#     body_listener: true
#     view:
#       view_response_listener: true
#     serializer:
#         serialize_null: true
#     body_converter:
#         enabled: true
#         # format_listener:
#         rules:
#             - { path: '^/api',  priorities: ['json'], fallback_format: json, exception_fallback_format: html, prefer_extension: true }
#             - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }